#!/bin/bash
cd ProjetMaven/
mvn clean compile assembly:single
java --module-path ~/install/javafx-sdk-10.2/lib --add-modules javafx.controls,javafx.fxml,javafx.swing -cp target/ProjetMaven-1.0-SNAPSHOT-jar-with-dependencies.jar Test
