#!/bin/bash
cd ProjetMaven/
mvn clean compile assembly:single
java -Dprism.forceGPU=true --add-modules javafx.controls,javafx.fxml,javafx.swing -cp target/ProjetMaven-1.0-SNAPSHOT-jar-with-dependencies.jar Test
